# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.

permalink:           pretty
relative_permalinks: true

# Setup
title:               Austen Myers
tagline:             'a data dude from earth. former myspace king. -ivory cherry blossom.'
description:         'built with love on earth.'
url:                 http://austenmyers.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Austen Myers
  url:               https://instagram.com/stentertainme.nt
  email:             austenmy [at] usc.edu

# Custom vars
version:             1.0.0

# plugins
plugins: [jekyll-paginate]
